name: Bug Report
description: File a bug report
title: ""
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please make sure there is no [existing issue](https://github.com/saat-sy/flutterfusion/issues) for the bug you encountered.
  
  - type: textarea
    id: description
    attributes:
      label: Describe the Issue
      description: A clear and concise description of the issue you encountered.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide the steps to reproduce the issue.
      placeholder: 1. Go to '...'
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behavior
      description: Add a clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem. You can drag and drop `png`, `jpg`, `gif`, etc. in this box.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false