name: New Feature
description: Suggest an idea for FlutterFusion.
labels: ["new"]
body:
  - type: textarea
    attributes:
      label: Describe the new feature
      description: A clear and concise description of what the new feature is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false